title: Python For All
description: > # this means to ignore newlines until "baseurl:"
  Venha programar em Python.
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.pytnonforall.com.br" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "../css/2017_style/img/logo-small-transparent.png"

social: 
  name: GDG Feira de Santana
  link: "https://www.facebook.com/gdgfsaba/"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2017_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/gdgfsaba/
  - title: twitter
    url: https://twitter.com/gdgfsaba/

# Build settings
markdown: kramdown
permalink: pretty